### ISSUE TITLE
Extremely large Count() value after a Merge

### ISSUE THREAD

**Issue by mediocregopher** [clarkduvall/hyperloglog#18]
So this is a super specific test case, and unfortunately I haven't had much luck in boiling it down farther. But for a very specific input we're seeing extremely high Count() values after Merge'ing a populated HLL+ into an empty one.

Attached is the input data: [hll.txt](https://github.com/clarkduvall/hyperloglog/files/647234/hll.txt)

This is the test code:

```go
package main

import (
	"fmt"
	"hash/fnv"
	"io"
	"log"

	"github.com/clarkduvall/hyperloglog"
)

func main() {
	a, _ := hyperloglog.NewPlus(12)

	for {
		var l string
		if _, err := fmt.Scanln(&l); err == io.EOF {
			break
		} else if err != nil {
			panic(err)
		}
		h := fnv.New64a()
		h.Write([]byte(l))
		a.Add(h)
		log.Printf("added val %q to hll, count is now: %d", l, a.Count())
	}

	b, _ := hyperloglog.NewPlus(12)
	b.Merge(a)
	log.Printf("b.Count: %d", b.Count())
}
```

To run:
```
cat hll.txt | ./hlltest
```

The output should end with something like:
```
2016/12/12 14:20:06 b.Count: 18446744073709551615
```

If you omit the last line like this:
```
cat hll.txt | head -n-1 | ./hlltest
```

You get a much more reasonable output:
```
2016/12/12 14:26:46 b.Count: 3099
```

Let me know if there's any other information you need to help debug this, thanks!

**Comment by clarkduvall** [comment]
Can you try again with the latest code? I believe it should be fixed.

**Comment by mediocregopher** [comment]
that seems to have done it, thanks for the quick turnaround! :D
