### ISSUE TITLE
Another case of really large Count value

### ISSUE THREAD

**Issue by mediocregopher** [clarkduvall/hyperloglog#21]
Similar to #18 I have another case where the `Count` method returns an insanely large value for a very specific set of inputs.

Here is the input data: [hll.txt](https://github.com/clarkduvall/hyperloglog/files/1020184/hll.txt)

And here is the script to test it:

```
package main

import (
	"fmt"
	"hash/fnv"
	"io"
	"log"

	"github.com/clarkduvall/hyperloglog"
)

func main() {
	a, _ := hyperloglog.NewPlus(12)

	for {
		var l string
		if _, err := fmt.Scanln(&l); err == io.EOF {
			break
		} else if err != nil {
			panic(err)
		}
		h := fnv.New64a()
		h.Write([]byte(l))
		a.Add(h)
		//log.Printf("added val %q to hll, count is now: %d", l, a.Count())
	}

	log.Printf("a.Count: %d", a.Count())
}
```

Like in #18 I narrowed down the dataset so that omitting the last line causes the large number to not be output:

```
 /tmp ▻ cat hll.txt | ./hlltest                                                   
2017/05/22 14:49:54 a.Count: 18446744073709551604                                 
 /tmp ▻ cat hll.txt | head -n-1| ./hlltest                                        
2017/05/22 14:50:04 a.Count: 20478
```

Let me know if there's anything I can do to help debug more, thanks!

**Comment by mediocregopher** [comment]
Thanks for fixing this :) one quick question, if I have a bunch of existing HLL's marshaled and stored using a pre-#22 version, and I take them out, unmarshal them, and `Merge` them using post-#22 is that going to break anything or cause incorrect results?

**Comment by clarkduvall** [comment]
There shouldn't be any issue with the existing HLLs, the fix was to some of the code calculating the count, which doesn't affect the underlying representation.

**Comment by mediocregopher** [comment]
Ah ok, I saw there was changes in the Add and Merge methods so I wasn't sure, but that's good to hear, thanks!
